language: rust
cache: cargo

install:
  - rustup component add rustfmt
  - rustup component add clippy
  - command -v cargo-audit >/dev/null 2>&1 || cargo install cargo-audit

branches:
  only:
    - develop

env:
  global:
    - RUST_BACKTRACE=1

matrix:
  allow_failures:
    - os: osx
  fast_finish: true
  include:
    - name: build
      rust: stable
      os: linux
      script:
        - cargo build --no-default-features --lib
        - cargo build --release --all --all-features
    - name: test (rustc 1.35.0)
      rust: 1.35.0
      os: linux
      script:
        - cargo test --release --all --all-features
    - name: test (rustc stable)
      rust: stable
      os: linux
      script:
        - cargo test --release --all --all-features
    - name: test (rustc stable/macos)
      rust: stable
      os: osx
      script:
        - cargo test --release --all --all-features
    - name: rustfmt
      rust: stable
      os: linux
      script:
        - cargo fmt -- --check
    - name: clippy
      rust: stable
      script:
        - cargo clippy
    - name: audit
      rust: stable
      os: linux
      script:
        - cargo audit
    - name: doc
      rust: stable
      os: linux
      script:
        - cargo doc --all --all-features
