os: Visual Studio 2017

environment:
  matrix:
    # Minimum supported rustc
    - channel: 1.35.0
      target: x86_64-pc-windows-msvc

    # Stable channel should always be supported too
    - channel: stable
      target: x86_64-pc-windows-msvc

branches:
  only:
    - develop

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup component add rustfmt --toolchain %channel%
  - rustup component add clippy --toolchain %channel%
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo test --all --release
