[package]
name        = "abscissa"
description = """
              Application microframework with support for command-line option parsing,
              configuration, error handling, logging, and shell interactions
              """
version     = "0.0.0" # Also update html_root_url in lib.rs when bumping this
license     = "Apache-2.0"
authors     = ["Tony Arcieri <tony@iqlusion.io>", "Murarth <murarth@gmail.com>", "David Tolnay <dtolnay@gmail.com>"]
homepage    = "https://github.com/iqlusioninc/crates/"
repository  = "https://github.com/iqlusioninc/crates/tree/master/abscissa"
readme      = "README.md"
categories  = ["command-line-interface", "rust-patterns", "web-programming"]
keywords    = ["application", "container", "microservices", "framework", "service"]

[badges]
circle-ci = { repository = "iqlusioninc/crates" }
appveyor  = { repository = "iqlusioninc/crates" }

[dependencies]
canonical-path = "0.1"
clear_on_drop = "0.2"
failure = { version = "0.1", default-features = false, features = ["std"] }
abscissa_derive = { version = "0", path = "abscissa_derive" }
lazy_static = "1"
log = { version = "0.4", optional = true }
semver = { version = "0.9", optional = true }
serde = { version = "1.0", optional = true }
simplelog = { version = "0.5", optional = true }
term = "0.5"
toml = { version = "0.4", optional = true }

[dev-dependencies]
assert_matches = "1.3"
serde_derive = "1.0"

[features]
application = ["config", "errors", "logging", "options", "semver", "status"]
config = ["secrets", "serde", "status", "toml"]
default = ["application"]
errors = []
logging = ["log", "simplelog"]
options = ["abscissa_derive/options"]
secrets = []
shell = ["errors"]
status = ["shell"]

[workspace]
members = [".", "abscissa_derive"]

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["consoleapi", "fileapi", "minwinbase", "minwindef", "processenv", "winbase", "winnt"] }

[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = "0.1"
